require("dotenv").config();
const express=require("express"),cors=require("cors"),path=require("path"),fs=require("fs"),crypto=require("crypto"),multer=require("multer"),http=require("http"),bcrypt=require("bcryptjs"),session=require("express-session"),rateLimit=require("express-rate-limit"),helmet=require("helmet"),Stripe=require("stripe");
const PgStore=require("connect-pg-simple")(session),{Pool}=require("pg"),{Server}=require("socket.io");
const app=express(),server=http.createServer(app),PORT=Number(process.env.PORT||3000),PROD=process.env.NODE_ENV==="production";
const DATABASE_URL=process.env.DATABASE_URL,SESSION_SECRET=process.env.SESSION_SECRET,APP_ORIGIN=String(process.env.APP_ORIGIN||"").replace(/\/$/,""),GEMINI_API_KEY=process.env.GEMINI_API_KEY,MESHY_API_KEY=process.env.MESHY_API_KEY,STRIPE_SECRET_KEY=process.env.STRIPE_SECRET_KEY,STRIPE_WEBHOOK_SECRET=process.env.STRIPE_WEBHOOK_SECRET,ELEVENLABS_API_KEY=process.env.ELEVENLABS_API_KEY,NARRATOR_MALE_VOICE_ID=process.env.NARRATOR_MALE_VOICE_ID,NARRATOR_FEMALE_VOICE_ID=process.env.NARRATOR_FEMALE_VOICE_ID;
const GEMINI_IMAGE_MODEL=["gemini-3.1-flash-lite-image","gemini-3.1-flash-image"].includes(process.env.GEMINI_IMAGE_MODEL)?process.env.GEMINI_IMAGE_MODEL:"gemini-3.1-flash-lite-image";
const PUBLIC_LEGAL_NAME=String(process.env.PUBLIC_LEGAL_NAME||"MixoLabs").trim(),PUBLIC_LEGAL_ADDRESS=String(process.env.PUBLIC_LEGAL_ADDRESS||"Business address available on request").trim(),PUBLIC_SUPPORT_EMAIL=String(process.env.PUBLIC_SUPPORT_EMAIL||"support@example.invalid").trim();
if(!DATABASE_URL)throw Error("DATABASE_URL is required.");
if(!SESSION_SECRET||SESSION_SECRET.length<32)throw Error("SESSION_SECRET must be at least 32 characters.");
const pool=new Pool({connectionString:DATABASE_URL,ssl:PROD?{rejectUnauthorized:false}:undefined,max:Number(process.env.DB_POOL_SIZE||10)});
const stripe=STRIPE_SECRET_KEY?new Stripe(STRIPE_SECRET_KEY):null;
const BILLING={
 creator:{kind:"subscription",credits:100,priceId:process.env.STRIPE_PRICE_CREATOR_MONTHLY},
 pro:{kind:"subscription",credits:230,priceId:process.env.STRIPE_PRICE_PRO_MONTHLY},
 studio:{kind:"subscription",credits:450,priceId:process.env.STRIPE_PRICE_STUDIO_MONTHLY},
 pack50:{kind:"payment",credits:50,priceId:process.env.STRIPE_PRICE_PACK_50},
 pack110:{kind:"payment",credits:110,priceId:process.env.STRIPE_PRICE_PACK_110},
 pack250:{kind:"payment",credits:250,priceId:process.env.STRIPE_PRICE_PACK_250}
};
const CUSTOM_MIN_PENCE=199,CUSTOM_MAX_PENCE=100000,CREDIT_COST_GBP=Number(process.env.CREDIT_COST_GBP||(GEMINI_IMAGE_MODEL==="gemini-3.1-flash-lite-image"?.04:.06));
if(!Number.isFinite(CREDIT_COST_GBP)||CREDIT_COST_GBP<=0)throw Error("CREDIT_COST_GBP must be a positive number.");
function customCredits(amountPence,monthly=false){const pounds=amountPence/100;if(!monthly)return Math.max(1,Math.floor((pounds-(pounds*.015+.20)-pounds*.28)/CREDIT_COST_GBP));const monthlyCredits=Math.floor((pounds-(pounds*.022+.20)-pounds*.22)/CREDIT_COST_GBP);return Math.max(customCredits(amountPence,false)+2,monthlyCredits)}
app.set("trust proxy",1);app.disable("x-powered-by");app.use(helmet({contentSecurityPolicy:false,crossOriginResourcePolicy:false}));app.use(cors({origin:APP_ORIGIN||true,credentials:true}));
app.post("/api/stripe/webhook",express.raw({type:"application/json",limit:"2mb"}),async(req,res)=>{if(!stripe||!STRIPE_WEBHOOK_SECRET)return res.status(503).send("Stripe is not configured.");let event;try{event=stripe.webhooks.constructEvent(req.body,req.get("stripe-signature"),STRIPE_WEBHOOK_SECRET)}catch(e){return res.status(400).send("Invalid webhook signature.")}try{await processStripeEvent(event);res.json({received:true})}catch(e){console.error("stripe_webhook_failed",{event:event.id,type:event.type,message:e.message});res.status(500).send("Webhook processing failed.")}});
app.use(express.json({limit:"50mb"}));
const sessionMiddleware=session({store:new PgStore({pool,tableName:"user_sessions",createTableIfMissing:true}),name:"mixolabs.sid",secret:SESSION_SECRET,resave:false,saveUninitialized:false,rolling:true,cookie:{httpOnly:true,secure:PROD,sameSite:"lax",maxAge:2592000000}});
app.use(sessionMiddleware);
app.use("/api",(req,res,next)=>{if(!["POST","PUT","PATCH","DELETE"].includes(req.method)||!APP_ORIGIN||req.get("origin")===APP_ORIGIN)return next();res.status(403).json({error:"Request origin is not allowed."})});
const authLimit=rateLimit({windowMs:900000,limit:20,standardHeaders:true,legacyHeaders:false}),genLimit=rateLimit({windowMs:60000,limit:12,standardHeaders:true,legacyHeaders:false}),communityLimit=rateLimit({windowMs:60000,limit:20,standardHeaders:true,legacyHeaders:false}),billingLimit=rateLimit({windowMs:60000,limit:8,standardHeaders:true,legacyHeaders:false}),narrationLimit=rateLimit({windowMs:60000,limit:20,standardHeaders:true,legacyHeaders:false});
const uploadsDir=path.join(__dirname,"uploads");fs.mkdirSync(uploadsDir,{recursive:true});app.use("/uploads",express.static(uploadsDir));app.use(express.static(__dirname,{index:false}));
const io=new Server(server,{cors:{origin:APP_ORIGIN||true,credentials:true}});io.engine.use(sessionMiddleware);
const storage=multer.diskStorage({destination:(_,__,cb)=>cb(null,uploadsDir),filename:(_,f,cb)=>cb(null,Date.now()+"-"+crypto.randomBytes(5).toString("hex")+path.extname(f.originalname||".jpg"))});
const upload=multer({storage,limits:{fileSize:10485760},fileFilter:(_,f,cb)=>/^image\//.test(f.mimetype)?cb(null,true):cb(Error("Images only"))});
async function migrate(){await pool.query(`
CREATE TABLE IF NOT EXISTS users(id UUID PRIMARY KEY,email TEXT NOT NULL UNIQUE,display_name VARCHAR(40) NOT NULL,password_hash TEXT NOT NULL,purchased_credits INTEGER NOT NULL DEFAULT 0 CHECK(purchased_credits>=0),subscription_credits INTEGER NOT NULL DEFAULT 0 CHECK(subscription_credits>=0),subscription_status TEXT NOT NULL DEFAULT 'none',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE users ADD COLUMN IF NOT EXISTS stripe_customer_id TEXT UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS stripe_subscription_id TEXT UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_plan TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_current_period_end TIMESTAMPTZ;
CREATE TABLE IF NOT EXISTS credit_ledger(id UUID PRIMARY KEY,user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,delta INTEGER NOT NULL,bucket TEXT NOT NULL CHECK(bucket IN('purchased','subscription')),reason TEXT NOT NULL,idempotency_key TEXT NOT NULL,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,idempotency_key));
CREATE TABLE IF NOT EXISTS stripe_events(event_id TEXT PRIMARY KEY,event_type TEXT NOT NULL,processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS community_posts(id UUID PRIMARY KEY,user_id UUID REFERENCES users(id) ON DELETE SET NULL,display_name VARCHAR(40) NOT NULL,prompt VARCHAR(1200) NOT NULL DEFAULT '',image_url TEXT,likes INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS community_messages(id UUID PRIMARY KEY,user_id UUID REFERENCES users(id) ON DELETE SET NULL,display_name VARCHAR(40) NOT NULL,message VARCHAR(800) NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS model_comparisons(id UUID PRIMARY KEY,user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,prompt_hash TEXT NOT NULL,has_exact_text BOOLEAN NOT NULL DEFAULT FALSE,left_model TEXT NOT NULL,right_model TEXT NOT NULL,left_ms INTEGER NOT NULL,right_ms INTEGER NOT NULL,preferred_model TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),voted_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS ledger_user_created_idx ON credit_ledger(user_id,created_at DESC);CREATE INDEX IF NOT EXISTS posts_created_idx ON community_posts(created_at DESC);CREATE INDEX IF NOT EXISTS messages_created_idx ON community_messages(created_at DESC);
CREATE INDEX IF NOT EXISTS comparisons_user_created_idx ON model_comparisons(user_id,created_at DESC);
WITH removable AS (SELECT u.id AS user_id,LEAST(u.purchased_credits,COALESCE(SUM(l.delta) FILTER(WHERE l.reason='starter_credit'),0))::integer AS amount FROM users u JOIN credit_ledger l ON l.user_id=u.id WHERE NOT EXISTS(SELECT 1 FROM credit_ledger paid WHERE paid.user_id=u.id AND paid.reason='stripe_credit_pack') GROUP BY u.id,u.purchased_credits),recorded AS (INSERT INTO credit_ledger(id,user_id,delta,bucket,reason,idempotency_key,metadata) SELECT md5('remove-starter-credits:'||user_id::text)::uuid,user_id,-amount,'purchased','starter_credit_removed','remove-starter-credits-v1',jsonb_build_object('removed',amount) FROM removable WHERE amount>0 ON CONFLICT(user_id,idempotency_key) DO NOTHING RETURNING user_id,-delta AS amount) UPDATE users u SET purchased_credits=GREATEST(0,u.purchased_credits-r.amount),updated_at=NOW() FROM recorded r WHERE u.id=r.user_id;`)}
const cleanEmail=v=>String(v||"").trim().toLowerCase(),validEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)&&v.length<=254;
const expose=u=>({id:u.id,email:u.email,displayName:u.display_name,credits:Number(u.purchased_credits)+Number(u.subscription_credits),purchasedCredits:Number(u.purchased_credits),subscriptionCredits:Number(u.subscription_credits),subscriptionStatus:u.subscription_status,subscriptionPlan:u.subscription_plan||null,subscriptionCurrentPeriodEnd:u.subscription_current_period_end||null});
async function getUser(id){return(await pool.query("SELECT * FROM users WHERE id=$1",[id])).rows[0]||null}
function requireAuth(req,res,next){if(!req.session.userId)return res.status(401).json({error:"Please log in to continue."});next()}
function requireDigitalConsent(req,res,next){if(req.body?.digitalConsent!==true)return res.status(400).json({error:"Confirm the immediate digital-supply and refund acknowledgement before checkout."});next()}
app.post("/api/auth/register",authLimit,async(req,res,next)=>{try{const displayName=String(req.body.displayName||"").trim().slice(0,40),email=cleanEmail(req.body.email),password=String(req.body.password||"");if(displayName.length<2)return res.status(400).json({error:"Display name must be at least 2 characters."});if(!validEmail(email))return res.status(400).json({error:"Enter a valid email address."});if(password.length<10||password.length>128)return res.status(400).json({error:"Password must be 10 to 128 characters."});const id=crypto.randomUUID(),hash=await bcrypt.hash(password,12),c=await pool.connect();try{await c.query("BEGIN");const u=(await c.query("INSERT INTO users(id,email,display_name,password_hash,purchased_credits) VALUES($1,$2,$3,$4,0) RETURNING *",[id,email,displayName,hash])).rows[0];await c.query("COMMIT");req.session.userId=id;req.session.save(e=>e?next(e):res.status(201).json({user:expose(u)}))}catch(e){await c.query("ROLLBACK");if(e.code==="23505")return res.status(409).json({error:"An account with that email already exists."});throw e}finally{c.release()}}catch(e){next(e)}});
app.post("/api/auth/login",authLimit,async(req,res,next)=>{try{const u=(await pool.query("SELECT * FROM users WHERE email=$1",[cleanEmail(req.body.email)])).rows[0];if(!u||!await bcrypt.compare(String(req.body.password||""),u.password_hash))return res.status(401).json({error:"Email or password is incorrect."});req.session.regenerate(e=>{if(e)return next(e);req.session.userId=u.id;req.session.save(x=>x?next(x):res.json({user:expose(u)}))})}catch(e){next(e)}});
app.post("/api/auth/logout",(req,res,next)=>req.session.destroy(e=>e?next(e):res.status(204).end()));
app.get("/api/auth/me",async(req,res,next)=>{try{if(!req.session.userId)return res.json({user:null});const u=await getUser(req.session.userId);if(!u)return req.session.destroy(()=>res.json({user:null}));res.json({user:expose(u)})}catch(e){next(e)}});
const billingItemFromPrice=priceId=>Object.entries(BILLING).find(([,x])=>x.priceId===priceId)?.[0]||null;
async function recordStripeEvent(event,work){const c=await pool.connect();try{await c.query("BEGIN");const fresh=await c.query("INSERT INTO stripe_events(event_id,event_type) VALUES($1,$2) ON CONFLICT DO NOTHING RETURNING event_id",[event.id,event.type]);if(!fresh.rowCount){await c.query("ROLLBACK");return}await work(c);await c.query("COMMIT")}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
async function addCredits(c,userId,amount,bucket,reason,key,metadata={}){const added=await c.query("INSERT INTO credit_ledger(id,user_id,delta,bucket,reason,idempotency_key,metadata) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(user_id,idempotency_key) DO NOTHING RETURNING id",[crypto.randomUUID(),userId,amount,bucket,reason,key,metadata]);if(added.rowCount)await c.query(`UPDATE users SET ${bucket==="subscription"?"subscription_credits":"purchased_credits"}=${bucket==="subscription"?"subscription_credits":"purchased_credits"}+$1,updated_at=NOW() WHERE id=$2`,[amount,userId]);return!!added.rowCount}
async function reverseRefundedPackCredits(c,event,charge){
 const paymentIntent=typeof charge.payment_intent==="string"?charge.payment_intent:charge.payment_intent?.id;
 if(!paymentIntent){console.warn("stripe_refund_unmatched",{event:event.id,charge:charge.id,reason:"missing_payment_intent"});return}
 const purchase=(await c.query("SELECT id,user_id,delta,metadata FROM credit_ledger WHERE reason='stripe_credit_pack' AND metadata->>'paymentIntent'=$1 ORDER BY created_at DESC LIMIT 1",[paymentIntent])).rows[0];
 if(!purchase){console.warn("stripe_refund_unmatched",{event:event.id,charge:charge.id,paymentIntent,reason:"purchase_not_found"});return}
 const grantedCredits=Math.max(0,Number(purchase.delta)||0),chargePence=Math.max(0,Number(charge.amount)||0),refundedPence=Math.max(0,Number(charge.amount_refunded)||0);
 if(!grantedCredits||!chargePence||!refundedPence)return;
 const targetCredits=refundedPence>=chargePence?grantedCredits:Math.floor(grantedCredits*refundedPence/chargePence);
 const previousTarget=Number((await c.query("SELECT COALESCE(MAX((metadata->>'targetCredits')::integer),0) AS target FROM credit_ledger WHERE user_id=$1 AND reason='stripe_credit_refund' AND metadata->>'paymentIntent'=$2",[purchase.user_id,paymentIntent])).rows[0]?.target||0);
 const incrementalTarget=Math.max(0,targetCredits-previousTarget),user=(await c.query("SELECT purchased_credits FROM users WHERE id=$1 FOR UPDATE",[purchase.user_id])).rows[0];
 if(!user)return;
 const removedCredits=Math.min(Number(user.purchased_credits)||0,incrementalTarget),unavailableCredits=incrementalTarget-removedCredits;
 await c.query("INSERT INTO credit_ledger(id,user_id,delta,bucket,reason,idempotency_key,metadata) VALUES($1,$2,$3,'purchased','stripe_credit_refund',$4,$5) ON CONFLICT(user_id,idempotency_key) DO NOTHING",[crypto.randomUUID(),purchase.user_id,-removedCredits,`stripe_refund:${event.id}`,{purchaseLedgerId:purchase.id,paymentIntent,chargeId:charge.id,chargePence,refundedPence,targetCredits,incrementalTarget,removedCredits,unavailableCredits}]);
 if(removedCredits)await c.query("UPDATE users SET purchased_credits=GREATEST(0,purchased_credits-$1),updated_at=NOW() WHERE id=$2",[removedCredits,purchase.user_id]);
}
async function processStripeEvent(event){const o=event.data.object;if(event.type==="checkout.session.completed"||event.type==="checkout.session.async_payment_succeeded"){return recordStripeEvent(event,async c=>{const item=o.metadata?.item,userId=o.metadata?.userId,offer=BILLING[item],credits=Number(o.metadata?.credits||offer?.credits),kind=o.metadata?.billingKind||offer?.kind;if(!userId||!Number.isInteger(credits)||credits<1)throw Error("Checkout metadata is invalid.");await c.query("UPDATE users SET stripe_customer_id=COALESCE(stripe_customer_id,$1),updated_at=NOW() WHERE id=$2",[String(o.customer),userId]);if(kind==="payment"&&o.payment_status==="paid")await addCredits(c,userId,credits,"purchased","stripe_credit_pack",`stripe_checkout:${o.id}`,{item:item||"custom",credits,amountPence:o.metadata?.amountPence,checkoutSessionId:o.id,paymentIntent:o.payment_intent})})}
 if(event.type==="charge.refunded"){return recordStripeEvent(event,async c=>reverseRefundedPackCredits(c,event,o))}
 if(event.type==="invoice.paid"){return recordStripeEvent(event,async c=>{const subscriptionId=typeof o.subscription==="string"?o.subscription:o.parent?.subscription_details?.subscription;if(!subscriptionId)return;const sub=await stripe.subscriptions.retrieve(subscriptionId),item=sub.metadata?.item||billingItemFromPrice(o.lines?.data?.[0]?.price?.id),offer=BILLING[item],credits=Number(sub.metadata?.credits||offer?.credits),userId=sub.metadata?.userId||(await c.query("SELECT id FROM users WHERE stripe_customer_id=$1",[String(o.customer)])).rows[0]?.id;if(!Number.isInteger(credits)||credits<1||!userId)throw Error("Subscription invoice could not be matched.");const key=`stripe_invoice:${o.id}`,exists=await c.query("SELECT 1 FROM credit_ledger WHERE user_id=$1 AND idempotency_key=$2",[userId,key]);if(!exists.rowCount){const u=(await c.query("SELECT subscription_credits FROM users WHERE id=$1 FOR UPDATE",[userId])).rows[0],grant=Math.max(0,Math.min(credits,credits*2-Number(u.subscription_credits)));if(grant)await addCredits(c,userId,grant,"subscription","stripe_subscription_renewal",key,{item:item||"custom",credits,amountPence:sub.metadata?.amountPence,invoiceId:o.id,subscriptionId});await c.query("UPDATE users SET stripe_customer_id=$1,stripe_subscription_id=$2,subscription_plan=$3,subscription_status='active',subscription_current_period_end=to_timestamp($4),updated_at=NOW() WHERE id=$5",[String(o.customer),subscriptionId,item||"custom",sub.current_period_end,userId])}})}
 if(event.type==="customer.subscription.updated"||event.type==="customer.subscription.deleted"){return recordStripeEvent(event,async c=>{const item=o.metadata?.item||billingItemFromPrice(o.items?.data?.[0]?.price?.id),status=event.type.endsWith("deleted")?"canceled":String(o.status||"none");await c.query("UPDATE users SET stripe_subscription_id=$1,subscription_plan=$2,subscription_status=$3,subscription_current_period_end=to_timestamp($4),updated_at=NOW() WHERE stripe_customer_id=$5 OR id=$6",[o.id,item,status,o.current_period_end||0,String(o.customer),o.metadata?.userId||null])})}
 return recordStripeEvent(event,async()=>{})}
app.get("/api/billing/status",requireAuth,async(req,res,next)=>{try{const u=await getUser(req.session.userId);res.json({enabled:!!stripe,testMode:!!STRIPE_SECRET_KEY?.startsWith("sk_test_"),user:expose(u)})}catch(e){next(e)}});
app.post("/api/billing/checkout",requireAuth,billingLimit,requireDigitalConsent,async(req,res,next)=>{try{if(!stripe)return res.status(503).json({error:"Payments are not configured yet."});const item=String(req.body.item||""),offer=BILLING[item];if(!offer||!offer.priceId)return res.status(400).json({error:"That billing option is not configured."});let u=await getUser(req.session.userId);if(offer.kind==="subscription"&&["active","trialing","past_due"].includes(u.subscription_status))return res.status(409).json({error:"You already have a subscription. Use Manage Billing to change or cancel it."});let customer=u.stripe_customer_id;if(!customer){const made=await stripe.customers.create({email:u.email,name:u.display_name,metadata:{userId:u.id}},{idempotencyKey:`customer:${u.id}`});customer=made.id;await pool.query("UPDATE users SET stripe_customer_id=$1,updated_at=NOW() WHERE id=$2",[customer,u.id])}const session=await stripe.checkout.sessions.create({mode:offer.kind,customer,line_items:[{price:offer.priceId,quantity:1}],success_url:`${APP_ORIGIN}/?billing=success&session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${APP_ORIGIN}/?billing=cancelled`,client_reference_id:u.id,metadata:{userId:u.id,item},...(offer.kind==="subscription"?{subscription_data:{metadata:{userId:u.id,item}}}:{payment_intent_data:{metadata:{userId:u.id,item}}})},{idempotencyKey:`checkout:${u.id}:${item}:${crypto.randomUUID()}`});res.json({url:session.url})}catch(e){next(e)}});
app.post("/api/billing/custom-checkout",requireAuth,billingLimit,requireDigitalConsent,async(req,res,next)=>{try{if(!stripe)return res.status(503).json({error:"Payments are not configured yet."});const amountPence=Number(req.body.amountPence),billingKind=req.body.billingKind==="subscription"?"subscription":"payment";if(!Number.isInteger(amountPence)||amountPence<CUSTOM_MIN_PENCE||amountPence>CUSTOM_MAX_PENCE)return res.status(400).json({error:"Choose an amount from £1.99 to £1,000.00."});let u=await getUser(req.session.userId);if(billingKind==="subscription"&&["active","trialing","past_due"].includes(u.subscription_status))return res.status(409).json({error:"You already have a subscription. Use Manage Billing to change or cancel it."});let customer=u.stripe_customer_id;if(!customer){const made=await stripe.customers.create({email:u.email,name:u.display_name,metadata:{userId:u.id}},{idempotencyKey:`customer:${u.id}`});customer=made.id;await pool.query("UPDATE users SET stripe_customer_id=$1,updated_at=NOW() WHERE id=$2",[customer,u.id])}const credits=customCredits(amountPence,billingKind==="subscription"),metadata={userId:u.id,item:"custom",billingKind,amountPence:String(amountPence),credits:String(credits)},price_data={currency:"gbp",unit_amount:amountPence,product_data:{name:billingKind==="subscription"?`MixoLabs Custom Monthly — ${credits} credits`:`MixoLabs Credit Pack — ${credits} credits`},...(billingKind==="subscription"?{recurring:{interval:"month"}}:{})};const checkout=await stripe.checkout.sessions.create({mode:billingKind,customer,line_items:[{price_data,quantity:1}],success_url:`${APP_ORIGIN}/?billing=success&session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${APP_ORIGIN}/?billing=cancelled`,client_reference_id:u.id,metadata,...(billingKind==="subscription"?{subscription_data:{metadata}}:{payment_intent_data:{metadata}})});res.json({url:checkout.url,credits})}catch(e){next(e)}});
app.post("/api/billing/portal",requireAuth,billingLimit,async(req,res,next)=>{try{if(!stripe)return res.status(503).json({error:"Payments are not configured yet."});const u=await getUser(req.session.userId);if(!u.stripe_customer_id)return res.status(400).json({error:"No billing account exists yet."});const p=await stripe.billingPortal.sessions.create({customer:u.stripe_customer_id,return_url:`${APP_ORIGIN}/?billing=returned`});res.json({url:p.url})}catch(e){next(e)}});
const COSTS={"1K":1,"2K":2,"4K":3};
async function debit(userId,amount,key,metadata){const c=await pool.connect();try{await c.query("BEGIN");if((await c.query("SELECT 1 FROM credit_ledger WHERE user_id=$1 AND idempotency_key=$2",[userId,key])).rowCount){await c.query("COMMIT");return{duplicate:true}}const u=(await c.query("SELECT * FROM users WHERE id=$1 FOR UPDATE",[userId])).rows[0];if(!u)throw Object.assign(Error("Account not found."),{status:401});if(Number(u.purchased_credits)+Number(u.subscription_credits)<amount)throw Object.assign(Error("Not enough credits."),{status:402});const sub=Math.min(Number(u.subscription_credits),amount),purchased=amount-sub,meta={...metadata,fromSubscription:sub,fromPurchased:purchased};await c.query("UPDATE users SET subscription_credits=subscription_credits-$1,purchased_credits=purchased_credits-$2,updated_at=NOW() WHERE id=$3",[sub,purchased,userId]);await c.query("INSERT INTO credit_ledger(id,user_id,delta,bucket,reason,idempotency_key,metadata) VALUES($1,$2,$3,$4,'generation',$5,$6)",[crypto.randomUUID(),userId,-amount,purchased?"purchased":"subscription",key,meta]);await c.query("COMMIT");return{metadata:meta}}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
async function refund(userId,amount,key,meta){const c=await pool.connect();try{await c.query("BEGIN");const x=await c.query("INSERT INTO credit_ledger(id,user_id,delta,bucket,reason,idempotency_key,metadata) VALUES($1,$2,$3,$4,'generation_refund',$5,$6) ON CONFLICT(user_id,idempotency_key) DO NOTHING RETURNING id",[crypto.randomUUID(),userId,amount,meta.fromPurchased?"purchased":"subscription",`refund:${key}`,meta]);if(x.rowCount)await c.query("UPDATE users SET subscription_credits=subscription_credits+$1,purchased_credits=purchased_credits+$2,updated_at=NOW() WHERE id=$3",[meta.fromSubscription||0,meta.fromPurchased||0,userId]);await c.query("COMMIT")}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
app.post("/api/gemini/generate",requireAuth,genLimit,async(req,res,next)=>{if(!GEMINI_API_KEY)return res.status(503).json({error:"Image generation is temporarily unavailable."});const size=req.body?.generationConfig?.imageConfig?.imageSize,operation=req.get("X-MixoLabs-Operation")==="angle-sheet"?"angle-sheet":"image",cost=operation==="angle-sheet"?2:COSTS[size],key=String(req.get("Idempotency-Key")||"");if(!cost)return res.status(400).json({error:"Invalid image quality."});if(!/^[A-Za-z0-9_-]{16,80}$/.test(key))return res.status(400).json({error:"A valid generation request ID is required."});let charge;try{charge=await debit(req.session.userId,cost,key,{imageSize:size,operation,model:GEMINI_IMAGE_MODEL});if(charge.duplicate)return res.status(409).json({error:"This generation request was already processed."});const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_IMAGE_MODEL}:generateContent?key=${encodeURIComponent(GEMINI_API_KEY)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(req.body),signal:AbortSignal.timeout(120000)}),data=await r.json().catch(()=>({}));if(!r.ok){await refund(req.session.userId,cost,key,charge.metadata);return res.status(r.status>=500?502:r.status).json({error:data?.error?.message||"Image generation failed. Your credits were returned."})}const u=await getUser(req.session.userId);res.set("X-MixoLabs-Credits",String(expose(u).credits)).json(data)}catch(e){if(charge&&!charge.duplicate)await refund(req.session.userId,cost,key,charge.metadata).catch(console.error);next(e)}});
app.get("/api/community/posts",async(_,res,next)=>{try{const rows=(await pool.query("SELECT id,display_name AS name,prompt,image_url AS \"imageUrl\",likes,EXTRACT(EPOCH FROM created_at)*1000 AS ts FROM community_posts ORDER BY created_at DESC LIMIT 500")).rows;res.json({posts:rows})}catch(e){next(e)}});
app.post("/api/community/posts",requireAuth,communityLimit,upload.single("image"),async(req,res,next)=>{try{const u=await getUser(req.session.userId),prompt=String(req.body.prompt||"").trim().slice(0,1200);if(!prompt&&!req.file)return res.status(400).json({error:"Add an image or prompt."});const rows=(await pool.query("INSERT INTO community_posts(id,user_id,display_name,prompt,image_url) VALUES($1,$2,$3,$4,$5) RETURNING id,display_name AS name,prompt,image_url AS \"imageUrl\",likes,EXTRACT(EPOCH FROM created_at)*1000 AS ts",[crypto.randomUUID(),u.id,u.display_name,prompt,req.file?"/uploads/"+req.file.filename:null])).rows;io.emit("community:new-post",rows[0]);res.json({post:rows[0]})}catch(e){next(e)}});
app.post("/api/community/posts/:id/like",requireAuth,communityLimit,async(req,res,next)=>{try{const rows=(await pool.query("UPDATE community_posts SET likes=likes+1 WHERE id=$1 RETURNING id,display_name AS name,prompt,image_url AS \"imageUrl\",likes,EXTRACT(EPOCH FROM created_at)*1000 AS ts",[req.params.id])).rows;if(!rows[0])return res.status(404).json({error:"Not found"});io.emit("community:updated",rows[0]);res.json({post:rows[0]})}catch(e){next(e)}});
app.get("/api/community/chat",async(_,res,next)=>{try{const rows=(await pool.query("SELECT id,display_name AS name,message,EXTRACT(EPOCH FROM created_at)*1000 AS ts FROM community_messages ORDER BY created_at DESC LIMIT 200")).rows;res.json({messages:rows.reverse()})}catch(e){next(e)}});
io.on("connection",socket=>{io.emit("community:online",io.engine.clientsCount);socket.on("community:chat-send",async(payload={})=>{try{const id=socket.request.session?.userId,u=id&&await getUser(id),message=String(payload.message||"").trim().slice(0,800);if(!u)return socket.emit("community:error",{error:"Please log in to chat."});if(!message)return;const item=(await pool.query("INSERT INTO community_messages(id,user_id,display_name,message) VALUES($1,$2,$3,$4) RETURNING id,display_name AS name,message,EXTRACT(EPOCH FROM created_at)*1000 AS ts",[crypto.randomUUID(),u.id,u.display_name,message])).rows[0];io.emit("community:chat-message",item)}catch(e){console.error("chat_send_failed",e);socket.emit("community:error",{error:"Message could not be sent."})}});socket.on("disconnect",()=>setTimeout(()=>io.emit("community:online",io.engine.clientsCount),50))});
function key(req,res,next){if(!MESHY_API_KEY)return res.status(503).json({error:"3D generation is temporarily unavailable."});next()}
async function meshy(p,o={}){const r=await fetch("https://api.meshy.ai"+p,{...o,headers:{Authorization:"Bearer "+MESHY_API_KEY,"Content-Type":"application/json",...(o.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(Error(d.message||d.error?.message||d.error||"Meshy error"),{status:r.status});return d}
const fail=(res,e)=>res.status(e.status||500).json({error:e.message});
app.post("/api/3d/from-image",requireAuth,key,async(req,res)=>{try{const image_url=req.body.image_url;if(!image_url)return res.status(400).json({error:"image_url is required."});const d=await meshy("/openapi/v1/image-to-3d",{method:"POST",body:JSON.stringify({image_url,ai_model:"latest",ultra_mode:req.body.ultra_mode!==false,should_texture:true,enable_pbr:req.body.enable_pbr!==false,texture_resolution:"4k",should_remesh:false,image_enhancement:true,moderation:true,target_formats:["glb","obj","fbx","stl","usdz","3mf"],auto_size:true,multi_view_thumbnails:true,origin_at:"bottom"})});res.json({id:d.result})}catch(e){fail(res,e)}});
app.get("/api/3d/from-image/status/:id",requireAuth,key,async(req,res)=>{try{res.json(await meshy("/openapi/v1/image-to-3d/"+encodeURIComponent(req.params.id)))}catch(e){fail(res,e)}});
app.post("/api/3d/create",requireAuth,key,async(req,res)=>{try{const d=await meshy("/openapi/v1/multi-image-to-3d",{method:"POST",body:JSON.stringify({image_urls:(req.body.images||[]).slice(0,4),ai_model:"latest",ultra_mode:!!req.body.ultra_mode,should_texture:true,enable_pbr:!!req.body.enable_pbr,should_remesh:true,target_formats:["glb","obj","fbx","stl","usdz","3mf"],origin_at:"bottom"})});res.json({id:d.result})}catch(e){fail(res,e)}});
app.get("/api/3d/status/:id",requireAuth,key,async(req,res)=>{try{res.json(await meshy("/openapi/v1/multi-image-to-3d/"+encodeURIComponent(req.params.id)))}catch(e){fail(res,e)}});
app.post("/api/3d/resize",requireAuth,key,async(req,res)=>{try{res.json({id:(await meshy("/openapi/v1/resize",{method:"POST",body:JSON.stringify({input_task_id:req.body.input_task_id,resize_height:Number(req.body.height_mm)/1000,origin_at:"bottom"})})).result})}catch(e){fail(res,e)}});
app.get("/api/3d/resize-status/:id",requireAuth,key,async(req,res)=>{try{res.json(await meshy("/openapi/v1/resize/"+encodeURIComponent(req.params.id)))}catch(e){fail(res,e)}});
app.post("/api/3d/convert",requireAuth,key,async(req,res)=>{try{res.json({id:(await meshy("/openapi/v1/convert",{method:"POST",body:JSON.stringify({model_url:req.body.model_url,target_formats:["glb","obj","fbx","stl","usdz","3mf"]})})).result})}catch(e){fail(res,e)}});
app.get("/api/3d/convert-status/:id",requireAuth,key,async(req,res)=>{try{res.json(await meshy("/openapi/v1/convert/"+encodeURIComponent(req.params.id)))}catch(e){fail(res,e)}});
const narrationConfigured=()=>!!(ELEVENLABS_API_KEY&&NARRATOR_MALE_VOICE_ID&&NARRATOR_FEMALE_VOICE_ID);
app.options("/api/narration",(_,res)=>narrationConfigured()?res.sendStatus(204):res.sendStatus(404));
app.post("/api/narration",narrationLimit,async(req,res,next)=>{try{if(!narrationConfigured())return res.status(503).json({error:"Natural narration is not configured yet."});const text=String(req.body?.text||"").trim(),voice=req.body?.voice==="male"?"male":"female",voiceId=voice==="male"?NARRATOR_MALE_VOICE_ID:NARRATOR_FEMALE_VOICE_ID;if(!text||text.length>1800)return res.status(400).json({error:"Narration text must be between 1 and 1,800 characters."});const r=await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${encodeURIComponent(voiceId)}?output_format=mp3_44100_128`,{method:"POST",headers:{"xi-api-key":ELEVENLABS_API_KEY,"Content-Type":"application/json","Accept":"audio/mpeg"},body:JSON.stringify({text,model_id:process.env.ELEVENLABS_MODEL_ID||"eleven_multilingual_v2",voice_settings:{stability:.48,similarity_boost:.82,style:.18,use_speaker_boost:true}}),signal:AbortSignal.timeout(30000)});if(!r.ok)throw Object.assign(Error("Natural narration provider could not create the audio."),{status:502});res.type("audio/mpeg").send(Buffer.from(await r.arrayBuffer()))}catch(e){next(e)}});
app.get("/api/health",async(_,res)=>{try{await pool.query("SELECT 1");res.json({ok:true,database:true,community:true,gemini_key_configured:!!GEMINI_API_KEY,gemini_image_model:GEMINI_IMAGE_MODEL,meshy_key_configured:!!MESHY_API_KEY,natural_narration_configured:narrationConfigured()})}catch(_){res.status(503).json({ok:false,database:false})}});
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function publicHtml(){return fs.readFileSync(path.join(__dirname,"index.html"),"utf8").replaceAll("{{LEGAL_NAME}}",escapeHtml(PUBLIC_LEGAL_NAME)).replaceAll("{{LEGAL_ADDRESS}}",escapeHtml(PUBLIC_LEGAL_ADDRESS)).replaceAll("{{SUPPORT_EMAIL}}",escapeHtml(PUBLIC_SUPPORT_EMAIL)).replace("</body>",'<script src="/random-infinite.js"></script></body>')}
app.get("/",(_,res)=>res.type("html").send(publicHtml()));app.get("*",(_,res)=>res.type("html").send(publicHtml()));
app.use((e,req,res,next)=>{console.error("request_failed",{path:req.path,message:e.message});if(res.headersSent)return next(e);res.status(e.status||500).json({error:e.status?e.message:"Something went wrong. Please try again."})});
migrate().then(()=>server.listen(PORT,()=>console.log(`MixoLabs running on port ${PORT}`))).catch(e=>{console.error("startup_failed",e);process.exit(1)});
